### ISSUE TITLE
High Sierra 10.13 无法正常使用

### ISSUE THREAD

**Issue by DanxiongLei** [vergilchoi/TimeFlies#1]
机器: iMac
系统版本: High Sierra 10.13
表现: 
能够正常安装，但是安装后在系统设置中即显示，无法正常使用。

**Comment by vergil-zhao** [comment]
mac 有个很奇怪的系统 bug，可以参考这里：

 [Screen Saver doesn't run on macOS High Sierra 10.13.0](https://github.com/JohnCoates/Aerial/issues/385)

更新到最新系统可以解决问题。

或者我已经用 OC 重写了，现在应该可以使用了，请下载最新的版本。
