### ISSUE TITLE
是否考虑显示当前时间?

### ISSUE THREAD

**Issue by cnfn** [vergilchoi/TimeFlies#2]
比如说在红框位置显示当前时间?
![image](https://user-images.githubusercontent.com/1445517/38551900-fbb6419e-3cec-11e8-91f7-e10050b24df7.png)

**Comment by vergil-zhao** [comment]
可以考虑加个设置页面，选择是否显示当前时间

**Comment by vergil-zhao** [comment]
v0.2.0 已增加时间
